# Generated by Django 5.1.1 on 2024-10-11 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountSystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capitalaccount',
            name='owner_market_subject',
        ),
        migrations.RemoveField(
            model_name='capitalaccount',
            name='owner_natural_person',
        ),
        migrations.RemoveField(
            model_name='capitalaccount',
            name='ttype',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='_from',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='to',
        ),
        migrations.RemoveField(
            model_name='human',
            name='WB',
        ),
        migrations.DeleteModel(
            name='CapitalAccountType',
        ),
        migrations.DeleteModel(
            name='CapitalAccount',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='Weibo',
        ),
    ]
