# Generated by Django 4.2.3 on 2024-04-16 10:53

from django.db import migrations
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jumpService', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicetype',
            old_name='defaultPort',
            new_name='port',
        ),
        migrations.AddField(
            model_name='servicetype',
            name='dashboardPort',
            field=simplepro.components.fields.IntegerField(blank=True, null=True, verbose_name='默认Dashboard端口'),
        ),
    ]
