# Generated by Django 4.2.3 on 2024-07-24 12:04

from django.db import migrations, models
import django.db.models.deletion
import simplepro.components.fields
import simplepro.components.fields.char_field
import simplepro.editor.fields
import simplepro.lib.pkHelper


class Migration(migrations.Migration):

    dependencies = [
        ('jumpService', '0002_rename_defaultport_servicetype_port_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': '品牌', 'verbose_name_plural': '品牌'},
        ),
        migrations.AlterModelOptions(
            name='servernew',
            options={'verbose_name': '物理服务器', 'verbose_name_plural': '物理服务器'},
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('createdAt', models.DateTimeField(auto_created=True, auto_now_add=True, db_index=True, null=True, verbose_name='创建时间')),
                ('id', models.CharField(default=simplepro.lib.pkHelper.uuid_generator, editable=False, max_length=48, primary_key=True, serialize=False)),
                ('updatedAt', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='最近更新时间')),
                ('deletedAt', models.DateTimeField(db_index=True, editable=False, null=True, verbose_name='被删除时间')),
                ('remark', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='小备注/标签')),
                ('info', simplepro.editor.fields.UETextField(blank=True, null=True, verbose_name='说明')),
                ('model', simplepro.components.fields.char_field.CharField(max_length=50, unique=True)),
                ('name', simplepro.components.fields.char_field.CharField(max_length=50, unique=True)),
                ('frequency', simplepro.components.fields.IntegerField(blank=True, null=True, verbose_name='频率(Ghz)')),
                ('brand', simplepro.components.fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jumpService.brand', verbose_name='品牌')),
            ],
            options={
                'ordering': ['-updatedAt'],
                'abstract': False,
            },
        ),
    ]
