# Generated by Django 4.2.3 on 2024-08-02 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jumpService', '0003_alter_brand_options_alter_servernew_options_cpu'),
    ]

    operations = [
        migrations.AddField(
            model_name='sshserviceuser',
            name='server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='jumpService.servernew', verbose_name='服务器'),
        ),
    ]
