# Generated by Django 4.2.3 on 2024-08-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumpService', '0004_sshserviceuser_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationsystem',
            name='sshPort',
            field=models.PositiveSmallIntegerField(blank=True, default=22, null=True, verbose_name='SSH端口'),
        ),
    ]
