# Generated by Django 4.2.3 on 2024-08-02 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jumpService', '0005_operationsystem_sshport'),
    ]

    operations = [
        migrations.AddField(
            model_name='sshserviceuser',
            name='system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='jumpService.operationsystem', verbose_name='操作系统'),
        ),
    ]
