# Generated by Django 4.2.3 on 2024-08-02 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jumpService', '0006_sshserviceuser_system'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SSHServiceUser',
            new_name='SystemUser',
        ),
    ]
