# Generated by Django 4.2.3 on 2024-08-02 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jumpService', '0007_rename_sshserviceuser_systemuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemuser',
            options={'verbose_name': '系统用户', 'verbose_name_plural': '系统用户'},
        ),
    ]
