# Generated by Django 4.2.3 on 2024-08-02 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jumpService', '0009_systemuser_unique_judge_by_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemuser',
            name='service',
        ),
    ]
