# Generated by Django 4.2.3 on 2024-08-02 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jumpService', '0010_remove_systemuser_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationsystem',
            name='rootPassword',
        ),
        migrations.RemoveField(
            model_name='operationsystem',
            name='rootUsername',
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='jumpService.servernew', verbose_name='服务器'),
        ),
    ]
