# Generated by Django 4.2.3 on 2024-08-02 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jumpService', '0011_remove_operationsystem_rootpassword_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemuser',
            name='server',
        ),
    ]
