# Generated by Django 4.2.3 on 2024-08-02 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jumpService', '0012_remove_systemuser_server'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SSHService',
        ),
    ]
