# Generated by Django 5.1.1 on 2024-11-15 01:30

import django.db.models.deletion
import simplepro.components.fields
import simplepro.components.fields.char_field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumpService', '0014_bt_ssl'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='operationsystemimage',
            name='operation_system_name_version_unique',
        ),
        migrations.AddField(
            model_name='operationsystemimage',
            name='build_number',
            field=simplepro.components.fields.char_field.CharField(blank=True, help_text='例如: 19045.5011, 3.10.0-1160.108.1.el7.x86_64', max_length=50, null=True, verbose_name='内部版本号'),
        ),
        migrations.AddField(
            model_name='operationsystemimage',
            name='code_name',
            field=simplepro.components.fields.char_field.CharField(blank=True, help_text='例如: Noble Numbat, Core', max_length=50, null=True, verbose_name='版本代号'),
        ),
        migrations.AddField(
            model_name='operationsystemimage',
            name='series',
            field=simplepro.components.fields.char_field.CharField(blank=True, help_text='例如: Windows 10, CentOS 7, Ubuntu 24.04', max_length=50, null=True, verbose_name='系列'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='device',
            field=simplepro.components.fields.ForeignKey(help_text='是指占用当前地址的网络设备', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ips', to='jumpService.netdevice', verbose_name='网络设备'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='net',
            field=simplepro.components.fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jumpService.net', verbose_name='所属网段'),
        ),
        migrations.AlterField(
            model_name='operationsystemimage',
            name='arch',
            field=simplepro.components.fields.char_field.CharField(blank=True, help_text='例如: x86_64, amd64, arm64', max_length=50, null=True, verbose_name='系统架构'),
        ),
        migrations.AlterField(
            model_name='operationsystemimage',
            name='isLTS',
            field=models.BooleanField(default=False, verbose_name='LTS版本'),
        ),
        migrations.AlterField(
            model_name='operationsystemimage',
            name='iso',
            field=models.FileField(blank=True, null=True, upload_to='system_images', verbose_name='安装镜像'),
        ),
        migrations.AlterField(
            model_name='operationsystemimage',
            name='name',
            field=simplepro.components.fields.char_field.CharField(help_text='例如: Ubuntu, CentOS, Windows, MacOS', max_length=50, verbose_name='系统分类'),
        ),
        migrations.AlterField(
            model_name='operationsystemimage',
            name='version',
            field=simplepro.components.fields.char_field.CharField(help_text='例如: 22H2, 7, 24.04', max_length=50, verbose_name='版本号'),
        ),
        migrations.AddConstraint(
            model_name='operationsystemimage',
            constraint=models.UniqueConstraint(fields=('name', 'series', 'version', 'arch'), name='operation_system_unique'),
        ),
    ]
