# Generated by Django 5.1.1 on 2024-11-15 01:52

import simplepro.components.fields.char_field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumpService', '0015_remove_operationsystemimage_operation_system_name_version_unique_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='operationsystemimage',
            name='operation_system_unique',
        ),
        migrations.AlterField(
            model_name='operationsystemimage',
            name='arch',
            field=simplepro.components.fields.char_field.CharField(blank=True, max_length=50, null=True, verbose_name='架构'),
        ),
        migrations.AlterField(
            model_name='operationsystemimage',
            name='build_number',
            field=simplepro.components.fields.char_field.CharField(blank=True, max_length=50, null=True, verbose_name='内部版本号'),
        ),
        migrations.AlterField(
            model_name='operationsystemimage',
            name='code_name',
            field=simplepro.components.fields.char_field.CharField(blank=True, max_length=50, null=True, verbose_name='版本代号'),
        ),
        migrations.AlterField(
            model_name='operationsystemimage',
            name='isLTS',
            field=models.BooleanField(default=False, verbose_name='LTS'),
        ),
        migrations.AlterField(
            model_name='operationsystemimage',
            name='name',
            field=simplepro.components.fields.char_field.CharField(max_length=50, verbose_name='系统分类'),
        ),
        migrations.AlterField(
            model_name='operationsystemimage',
            name='series',
            field=simplepro.components.fields.char_field.CharField(blank=True, max_length=50, null=True, verbose_name='系列'),
        ),
        migrations.AlterField(
            model_name='operationsystemimage',
            name='version',
            field=simplepro.components.fields.char_field.CharField(max_length=50, verbose_name='版本号'),
        ),
        migrations.AddConstraint(
            model_name='operationsystemimage',
            constraint=models.UniqueConstraint(fields=('name', 'series', 'version', 'build_number', 'arch'), name='operation_system_unique'),
        ),
    ]
