# Generated by Django 5.1.1 on 2024-11-15 01:53

import simplepro.components.fields.char_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jumpService', '0016_remove_operationsystemimage_operation_system_unique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationsystemimage',
            name='series',
            field=simplepro.components.fields.char_field.CharField(max_length=50, null=True, verbose_name='系列'),
        ),
    ]
