# Generated by Django 5.0.12 on 2025-03-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumpService', '0017_alter_operationsystemimage_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='dashboard_port_status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Dashboard端口连通性状态'),
        ),
        migrations.AddField(
            model_name='service',
            name='last_check_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近一次检测时间'),
        ),
        migrations.AddField(
            model_name='service',
            name='port_status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='端口连通性状态'),
        ),
        migrations.AddField(
            model_name='service',
            name='wafPort',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='WAF端口'),
        ),
        migrations.AddField(
            model_name='service',
            name='waf_port_status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='WAF端口连通性状态'),
        ),
    ]
