# Generated by Django 5.0.12 on 2025-03-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumpService', '0018_service_dashboard_port_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='dashboard_port_status',
        ),
        migrations.RemoveField(
            model_name='service',
            name='last_check_time',
        ),
        migrations.RemoveField(
            model_name='service',
            name='port_status',
        ),
        migrations.RemoveField(
            model_name='service',
            name='waf_port_status',
        ),
        migrations.AddField(
            model_name='service',
            name='lastChecked',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后检测时间'),
        ),
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('ok', '正常'), ('fail', '故障'), ('checking', '检测中'), ('unknown', '未知')], default='unknown', max_length=20, verbose_name='连通状态'),
        ),
        migrations.AlterField(
            model_name='service',
            name='wafPort',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='WAF代理端口'),
        ),
    ]
