# Generated by Django 5.0.12 on 2025-03-26 13:05

import simplepro.components.fields
import simplepro.components.fields.char_field
import simplepro.editor.fields
import simplepro.lib.pkHelper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumpService', '0019_remove_service_dashboard_port_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectiveStatus',
            fields=[
                ('createdAt', models.DateTimeField(auto_created=True, auto_now_add=True, db_index=True, null=True, verbose_name='创建时间')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='最近更新时间')),
                ('deletedAt', models.DateTimeField(db_index=True, editable=False, null=True, verbose_name='被删除时间')),
                ('info', simplepro.editor.fields.UETextField(blank=True, null=True, verbose_name='说明')),
                ('id', simplepro.components.fields.char_field.CharField(default=simplepro.lib.pkHelper.uuid_generator, editable=False, max_length=48, primary_key=True, serialize=False)),
                ('remark', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='备注')),
                ('status', models.CharField(choices=[('ok', '正常'), ('fail', '故障'), ('checking', '检测中'), ('unknown', '未知')], default='unknown', max_length=20, verbose_name='连通状态')),
                ('lastChecked', models.DateTimeField(blank=True, null=True, verbose_name='最后检测时间')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='service',
            name='lastChecked',
        ),
        migrations.RemoveField(
            model_name='service',
            name='status',
        ),
        migrations.AddField(
            model_name='service',
            name='connectiveStatusHistory',
            field=simplepro.components.fields.ManyToManyField(to='jumpService.connectivestatus'),
        ),
    ]
