# Generated by Django 5.0.12 on 2025-03-26 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumpService', '0020_connectivestatus_remove_service_lastchecked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='connectiveStatusHistory',
        ),
        migrations.AddField(
            model_name='connectivestatus',
            name='service',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='connectStatusHistory', to='jumpService.service'),
            preserve_default=False,
        ),
    ]
