# Generated by Django 4.2.20 on 2025-04-06 10:22

from django.db import migrations, models
import django.db.models.deletion
import simplepro.editor.fields
import simplepro.lib.pkHelper


class Migration(migrations.Migration):

    dependencies = [
        ('jumpService', '0021_remove_service_connectivestatushistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceURL',
            fields=[
                ('createdAt', models.DateTimeField(auto_created=True, auto_now_add=True, db_index=True, null=True, verbose_name='创建时间')),
                ('id', models.CharField(default=simplepro.lib.pkHelper.uuid_generator, editable=False, max_length=48, primary_key=True, serialize=False)),
                ('updatedAt', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='最近更新时间')),
                ('deletedAt', models.DateTimeField(db_index=True, editable=False, null=True, verbose_name='被删除时间')),
                ('remark', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='小备注/标签')),
                ('info', simplepro.editor.fields.UETextField(blank=True, null=True, verbose_name='说明')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='名称')),
                ('url', models.URLField(verbose_name='访问地址')),
                ('is_default', models.BooleanField(default=False, verbose_name='默认入口')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='jumpService.service', verbose_name='服务')),
            ],
            options={
                'verbose_name': '服务入口',
                'verbose_name_plural': '服务入口',
                'ordering': ['-is_default', '-updatedAt'],
            },
        ),
    ]
