# Generated by Django 4.2.20 on 2025-04-15 01:54

from django.db import migrations, models
import django.db.models.deletion
import simplepro.components.fields.char_field
import simplepro.editor.fields
import simplepro.lib.pkHelper


class Migration(migrations.Migration):

    dependencies = [
        ('jumpService', '0022_serviceurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('createdAt', models.DateTimeField(auto_created=True, auto_now_add=True, db_index=True, null=True, verbose_name='创建时间')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='最近更新时间')),
                ('deletedAt', models.DateTimeField(db_index=True, editable=False, null=True, verbose_name='被删除时间')),
                ('info', simplepro.editor.fields.UETextField(blank=True, null=True, verbose_name='说明')),
                ('id', simplepro.components.fields.char_field.CharField(default=simplepro.lib.pkHelper.uuid_generator, editable=False, max_length=48, primary_key=True, serialize=False)),
                ('remark', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='备注')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='协议名称')),
                ('default_port', models.PositiveIntegerField(blank=True, null=True, verbose_name='默认端口')),
                ('is_web_protocol', models.BooleanField(default=False, verbose_name='是否Web协议')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '协议',
                'verbose_name_plural': '协议',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='serviceurl',
            name='url',
        ),
        migrations.AddField(
            model_name='serviceurl',
            name='host',
            field=models.CharField(default='', max_length=255, verbose_name='主机'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceurl',
            name='is_dashboard',
            field=models.BooleanField(default=False, verbose_name='是否面板'),
        ),
        migrations.AddField(
            model_name='serviceurl',
            name='path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='路径'),
        ),
        migrations.AddField(
            model_name='serviceurl',
            name='port',
            field=models.PositiveIntegerField(default=8000, verbose_name='端口'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceurl',
            name='protocol',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, to='jumpService.protocol', verbose_name='协议'),
            preserve_default=False,
        ),
    ]
