# Generated by Django 4.2.20 on 2026-01-28 19:53

from django.db import migrations
import simplepro.components.fields.char_field


class Migration(migrations.Migration):

    dependencies = [
        ('jumpService', '0025_serviceurl_domain_alter_operationsystem_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='net',
            name='gatewayIP',
            field=simplepro.components.fields.char_field.CharField(blank=True, default=None, max_length=15, null=True, verbose_name='网关地址'),
        ),
    ]
