# Generated by Django 4.2.20 on 2026-01-28 22:28

from django.db import migrations, models
import django.db.models.deletion
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jumpService', '0026_net_gatewayip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddress',
            name='net',
            field=simplepro.components.fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ips', to='jumpService.net', verbose_name='所属网段'),
        ),
        migrations.AlterField(
            model_name='servernew',
            name='hoster',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '阿里云'), (2, '腾讯云'), (3, '哈密市希望科技有限公司'), (4, '新疆丝路融创网络科技有限公司（局域网）'), (5, '政务云')], null=True, verbose_name='托管方'),
        ),
    ]
