# Generated by Django 4.2.20 on 2026-01-29 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jumpService', '0027_alter_ipaddress_net_alter_servernew_hoster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operationsystem',
            old_name='sshPort',
            new_name='remoteAccessPort',
        ),
        migrations.DeleteModel(
            name='ElasticSearch',
        ),
    ]
