# Generated by Django 4.2.20 on 2026-01-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumpService', '0028_rename_sshport_operationsystem_remoteaccessport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationsystem',
            name='remoteAccessPort',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='远程登录/控制/访问端口'),
        ),
    ]
