# Generated by Django 4.2.20 on 2026-01-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumpService', '0029_alter_operationsystem_remoteaccessport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationsystem',
            name='remoteAccessPort',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='远程控制端口'),
        ),
    ]
