# Generated by Django 4.2.20 on 2026-01-30 12:10

from django.db import migrations
import simplepro.components.fields.char_field
import simplepro.components.fields.input_password_field


class Migration(migrations.Migration):

    dependencies = [
        ('jumpService', '0030_alter_operationsystem_remoteaccessport'),
    ]

    operations = [
        migrations.AddField(
            model_name='netdevice',
            name='webControlAddress',
            field=simplepro.components.fields.char_field.CharField(blank=True, max_length=255, null=True, verbose_name='WEB管理页面访问地址'),
        ),
        migrations.AddField(
            model_name='netdevice',
            name='webControlPassword',
            field=simplepro.components.fields.input_password_field.PasswordInputField(blank=True, max_length=32, null=True, verbose_name='管理页密码'),
        ),
        migrations.AddField(
            model_name='netdevice',
            name='webControlUsername',
            field=simplepro.components.fields.char_field.CharField(blank=True, max_length=32, null=True, verbose_name='管理员用户名'),
        ),
    ]
