# Generated by Django 4.2.20 on 2026-01-30 12:13

from django.db import migrations
import simplepro.components.fields.char_field
import simplepro.components.fields.input_password_field


class Migration(migrations.Migration):

    dependencies = [
        ('jumpService', '0031_netdevice_webcontroladdress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='adminAddress',
            field=simplepro.components.fields.char_field.CharField(blank=True, max_length=255, null=True, verbose_name='管理页面访问地址'),
        ),
        migrations.AlterField(
            model_name='router',
            name='adminPassword',
            field=simplepro.components.fields.input_password_field.PasswordInputField(blank=True, max_length=32, null=True, verbose_name='管理页密码'),
        ),
    ]
