# Generated by Django 4.2.20 on 2026-01-30 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jumpService', '0032_alter_router_adminaddress_alter_router_adminpassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='router',
            name='adminAddress',
        ),
        migrations.RemoveField(
            model_name='router',
            name='adminPassword',
        ),
    ]
