# Generated by Django 4.2.20 on 2026-01-30 12:30

from django.db import migrations, models
import django.db.models.deletion
import simplepro.components.fields.char_field
import simplepro.components.fields.input_password_field
import simplepro.editor.fields
import simplepro.lib.pkHelper


class Migration(migrations.Migration):

    dependencies = [
        ('jumpService', '0033_remove_router_adminaddress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VPNDevice',
            fields=[
                ('servernew_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jumpService.servernew')),
            ],
            options={
                'verbose_name': 'VPN设备',
                'verbose_name_plural': 'VPN设备',
            },
            bases=('jumpService.servernew',),
        ),
        migrations.CreateModel(
            name='VPNService',
            fields=[
                ('createdAt', models.DateTimeField(auto_created=True, auto_now_add=True, db_index=True, null=True, verbose_name='创建时间')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='最近更新时间')),
                ('deletedAt', models.DateTimeField(db_index=True, editable=False, null=True, verbose_name='被删除时间')),
                ('info', simplepro.editor.fields.UETextField(blank=True, null=True, verbose_name='说明')),
                ('id', simplepro.components.fields.char_field.CharField(default=simplepro.lib.pkHelper.uuid_generator, editable=False, max_length=48, primary_key=True, serialize=False)),
                ('remark', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='备注')),
                ('port', models.PositiveIntegerField(db_index=True, default=8888, verbose_name='端口')),
                ('path', models.TextField(blank=True, null=True, verbose_name='路径')),
                ('vpn_type', simplepro.components.fields.char_field.CharField(choices=[('openvpn', 'OpenVPN'), ('wireguard', 'WireGuard'), ('ipsec', 'IPSec'), ('l2tp', 'L2TP'), ('pptp', 'PPTP'), ('sstp', 'SSTP')], default='openvpn', max_length=20, verbose_name='VPN类型')),
                ('protocol', simplepro.components.fields.char_field.CharField(choices=[('udp', 'UDP'), ('tcp', 'TCP')], default='udp', max_length=10, verbose_name='协议')),
                ('subnet', simplepro.components.fields.char_field.CharField(blank=True, max_length=50, null=True, verbose_name='虚拟网段')),
                ('public_host', simplepro.components.fields.char_field.CharField(blank=True, max_length=255, null=True, verbose_name='公网连接地址')),
                ('config_template', models.TextField(blank=True, null=True, verbose_name='配置模板')),
                ('server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_services', to='jumpService.servernew', verbose_name='服务器')),
            ],
            options={
                'verbose_name': 'VPN服务',
                'verbose_name_plural': 'VPN服务',
            },
        ),
        migrations.AlterField(
            model_name='dbservice',
            name='server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_services', to='jumpService.servernew', verbose_name='服务器'),
        ),
        migrations.CreateModel(
            name='VPNUser',
            fields=[
                ('createdAt', models.DateTimeField(auto_created=True, auto_now_add=True, db_index=True, null=True, verbose_name='创建时间')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='最近更新时间')),
                ('deletedAt', models.DateTimeField(db_index=True, editable=False, null=True, verbose_name='被删除时间')),
                ('remark', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='小备注/标签')),
                ('info', simplepro.editor.fields.UETextField(blank=True, null=True, verbose_name='说明')),
                ('id', models.CharField(default=simplepro.lib.pkHelper.uuid_generator, max_length=48, primary_key=True, serialize=False)),
                ('owner', models.CharField(blank=True, max_length=50, null=True, verbose_name='使用者')),
                ('username', simplepro.components.fields.char_field.CharField(max_length=32, null=True, verbose_name='用户名')),
                ('password', simplepro.components.fields.input_password_field.PasswordInputField(max_length=32, null=True, verbose_name='密码')),
                ('hasRootPriority', models.BooleanField(blank=True, default=False, verbose_name='拥有root权限')),
                ('client_config', models.TextField(blank=True, null=True, verbose_name='客户端配置')),
                ('is_active', models.BooleanField(default=True, verbose_name='激活状态')),
                ('expired_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vpn_users', to='jumpService.vpnservice', verbose_name='所属VPN服务')),
            ],
            options={
                'verbose_name': 'VPN用户',
                'verbose_name_plural': 'VPN用户',
            },
        ),
    ]
