# Generated by Django 4.2.20 on 2026-02-08 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumpService', '0034_vpndevice_vpnservice_alter_dbservice_server_vpnuser'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='portmap',
            name='unique_p2p',
        ),
        migrations.AddConstraint(
            model_name='portmap',
            constraint=models.UniqueConstraint(fields=('left', 'right', 'leftPort', 'rightPort'), name='unique_p2p'),
        ),
    ]
