# Generated by Django 4.2.29 on 2026-03-10 02:05

from django.db import migrations, models
import django.db.models.deletion
import simplepro.components.fields
import simplepro.components.fields.char_field
import simplepro.components.fields.input_password_field
import simplepro.editor.fields
import simplepro.lib.pkHelper


class Migration(migrations.Migration):

    dependencies = [
        ('jumpService', '0035_remove_portmap_unique_p2p_portmap_unique_p2p'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSystem',
            fields=[
                ('createdAt', models.DateTimeField(auto_created=True, auto_now_add=True, db_index=True, null=True, verbose_name='创建时间')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='最近更新时间')),
                ('deletedAt', models.DateTimeField(db_index=True, editable=False, null=True, verbose_name='被删除时间')),
                ('info', simplepro.editor.fields.UETextField(blank=True, null=True, verbose_name='说明')),
                ('id', simplepro.components.fields.char_field.CharField(default=simplepro.lib.pkHelper.uuid_generator, editable=False, max_length=48, primary_key=True, serialize=False)),
                ('name', simplepro.components.fields.char_field.CharField(max_length=50, unique=True, verbose_name='名称')),
                ('remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '用户体系',
                'verbose_name_plural': '用户体系',
            },
        ),
        migrations.CreateModel(
            name='UnifiedServiceUser',
            fields=[
                ('createdAt', models.DateTimeField(auto_created=True, auto_now_add=True, db_index=True, null=True, verbose_name='创建时间')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='最近更新时间')),
                ('deletedAt', models.DateTimeField(db_index=True, editable=False, null=True, verbose_name='被删除时间')),
                ('info', simplepro.editor.fields.UETextField(blank=True, null=True, verbose_name='说明')),
                ('id', simplepro.components.fields.char_field.CharField(default=simplepro.lib.pkHelper.uuid_generator, editable=False, max_length=48, primary_key=True, serialize=False)),
                ('owner', models.CharField(blank=True, max_length=50, null=True, verbose_name='使用者')),
                ('username', simplepro.components.fields.char_field.CharField(max_length=32, null=True, verbose_name='用户名')),
                ('password', simplepro.components.fields.input_password_field.PasswordInputField(max_length=32, null=True, verbose_name='密码')),
                ('hasRootPriority', models.BooleanField(blank=True, default=False, verbose_name='拥有root权限')),
                ('remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
                ('group', simplepro.components.fields.IntegerField(blank=True, choices=[(0, 'root:x:0:'), (1, 'bin:x:1:'), (2, 'daemon:x:2:'), (3, 'sys:x:3:'), (4, 'adm:x:4:'), (5, 'tty:x:5:'), (6, 'disk:x:6:'), (7, 'lp:x:7:'), (8, 'mem:x:8:'), (9, 'kmem:x:9:'), (10, 'wheel:x:10:'), (11, 'cdrom:x:11:'), (12, 'mail:x:12:postfix'), (13, 'man:x:15:'), (14, 'dialout:x:18:'), (15, 'floppy:x:19:'), (16, 'games:x:20:'), (17, 'tape:x:33:')], null=True, verbose_name='用户组')),
                ('client_config', models.TextField(blank=True, null=True, verbose_name='客户端配置')),
                ('is_active', models.BooleanField(default=True, verbose_name='激活状态')),
                ('expired_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('user_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='jumpService.usersystem', verbose_name='所属用户体系')),
            ],
            options={
                'verbose_name': '统一服务用户',
                'verbose_name_plural': '统一服务用户',
            },
        ),
        migrations.AddField(
            model_name='dbservice',
            name='user_system',
            field=simplepro.components.fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jumpService.usersystem', verbose_name='用户体系'),
        ),
        migrations.AddField(
            model_name='operationsystem',
            name='user_system',
            field=simplepro.components.fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jumpService.usersystem', verbose_name='用户体系'),
        ),
        migrations.AddField(
            model_name='service',
            name='user_system',
            field=simplepro.components.fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jumpService.usersystem', verbose_name='用户体系'),
        ),
        migrations.AddField(
            model_name='vpnservice',
            name='user_system',
            field=simplepro.components.fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jumpService.usersystem', verbose_name='用户体系'),
        ),
        migrations.AddConstraint(
            model_name='unifiedserviceuser',
            constraint=models.UniqueConstraint(fields=('user_system', 'username'), name='unique_user_in_system'),
        ),
    ]
