# Generated by Django 4.2.29 on 2026-03-10 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('jumpService', '0036_usersystem_unifiedserviceuser_dbservice_user_system_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersystem',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='主服务类型'),
        ),
        migrations.AddField(
            model_name='usersystem',
            name='object_id',
            field=models.CharField(blank=True, max_length=48, null=True, verbose_name='主服务ID'),
        ),
    ]
